# Generated by Django 2.2.17 on 2020-12-11 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='gov_id',
            field=models.CharField(max_length=20, unique=True, verbose_name='Cédula'),
        ),
    ]
