# Generated by Django 2.2.17 on 2020-12-11 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20201211_1413'),
    ]

    operations = [
        migrations.AlterField(
            model_name='disableddate',
            name='date_time',
            field=models.DateTimeField(unique=True, verbose_name='Fecha y Hora'),
        ),
        migrations.AlterField(
            model_name='person',
            name='first_name',
            field=models.CharField(db_index=True, max_length=100, verbose_name='Nombre'),
        ),
        migrations.AlterField(
            model_name='person',
            name='last_name',
            field=models.CharField(db_index=True, max_length=100, verbose_name='Apellido'),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='date_time',
            field=models.DateTimeField(db_index=True, verbose_name='Fecha y Hora'),
        ),
        migrations.AlterUniqueTogether(
            name='schedule',
            unique_together={('day', 'time')},
        ),
    ]
