# Generated by Django 2.2.17 on 2020-12-11 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20201211_1418'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedule',
            name='persons_limit',
            field=models.PositiveSmallIntegerField(default=100, verbose_name='Cant. máx. de personas'),
        ),
    ]
